headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/mac/A2B-LIFT/website"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run server:build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/referral/:code"
to = "/login.html?ref=:code#register"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/ref/:code"
to = "/login.html?ref=:code#register"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/r/:code"
to = "/login.html?ref=:code#register"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]