[build]
  publish = "website"

[[redirects]]
  from = "/referral/*"
  to = "https://api-production-0783.up.railway.app/referral/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ref/*"
  to = "https://api-production-0783.up.railway.app/ref/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/r/*"
  to = "https://api-production-0783.up.railway.app/r/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
